spring:
  application.name: trippals
  config:
    import: classpath:config-datasource.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: info
    com.ssafy.trippals: debug