spring:
  application.name: trippals
  config:
    import: classpath:config-datasource.yml

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml

logging:
  level:
    root: info
    com.ssafy.trippals: debug